In [62]:
import pickle

In [63]:
with open('credit.pkl', 'rb') as f:
  x_treinamento, y_treinamento, x_teste, y_teste = pickle.load(f)

In [64]:
import numpy as np

In [65]:
X_credit = np.concatenate((x_treinamento, x_teste), axis=0)
Y_credit = np.concatenate((y_treinamento, y_teste), axis=0)

# Carregando Modelos Salvos

In [66]:
!pip install skops
from skops.io import load

In [67]:
rede_neural = load('rede_neural_finalizada.skops', trusted=True)
arvore = load('arvore_finalizada.skops', trusted=True)
svm = load('svm_finalizada.skops', trusted=True)

In [68]:
novo_registro = X_credit[0]
novo_registro

array([-1.3754462 ,  0.50631087,  0.10980934])

In [69]:
novo_registro.shape

(3,)

In [70]:
novo_registro = novo_registro.reshape(1,-1)
novo_registro.shape

(1, 3)

In [71]:
rede_neural.predict(novo_registro)

array([0])

In [72]:
arvore.predict(novo_registro)

array([0])

In [73]:
svm.predict(novo_registro)

array([0])

# Combinando mais de um classificador

In [74]:
novo_registro = X_credit[0]
novo_registro = novo_registro.reshape(1,-1)
novo_registro, novo_registro.shape

(array([[-1.3754462 ,  0.50631087,  0.10980934]]), (1, 3))

In [75]:
resposta_rede = rede_neural.predict(novo_registro)
resposta_arvore = arvore.predict(novo_registro)
resposta_svm = svm.predict(novo_registro)

In [76]:
resposta_rede[0], resposta_arvore[0], resposta_svm[0]

(0, 0, 0)

In [77]:
paga = 0
nao_paga = 0

if resposta_rede[0] == 1:
  nao_paga += 1
else:
  paga += 1

if resposta_arvore[0] == 1:
  nao_paga += 1
else:
  paga += 1

if resposta_svm[0] == 1:
  nao_paga += 1
else:
  paga += 1

if paga > nao_paga:
  print("Pagará o emprestimo")
elif paga == nao_paga:
  print("Empate")
else:
  print("Não paga o emprestimo")

Pagará o emprestimo


# Rejeição de classificadores

In [78]:
novo_registro = X_credit[0]
novo_registro = novo_registro.reshape(1,-1)
novo_registro, novo_registro.shape

(array([[-1.3754462 ,  0.50631087,  0.10980934]]), (1, 3))

In [79]:
resposta_rede = rede_neural.predict(novo_registro)
resposta_arvore = arvore.predict(novo_registro)
resposta_svm = svm.predict(novo_registro)

In [80]:
resposta_rede[0], resposta_arvore[0], resposta_svm[0]

(0, 0, 0)

In [81]:
# probabilidade do modelo
probabilidade_rede_neural = rede_neural.predict_proba(novo_registro)
probabilidade_rede_neural

array([[1.00000000e+00, 3.35482391e-17]])

In [82]:
confianca_rede_neural = probabilidade_rede_neural.max()
confianca_rede_neural

1.0

In [83]:
probabilidade_arvore = arvore.predict_proba(novo_registro)
probabilidade_arvore

array([[1., 0.]])

In [84]:
confianca_arvore = probabilidade_arvore.max()
confianca_arvore

1.0

In [85]:
probabilidade_svm = svm.predict_proba(novo_registro)
confianca_svm = probabilidade_svm.max()
confianca_svm

0.9999978733317746

In [87]:
paga = 0
nao_paga = 0
confianca_minima = 0.999999
algoritmos = 0

if confianca_rede_neural >= confianca_minima:
  algoritmos += 1
  if resposta_rede[0] == 1:
    nao_paga += 1
  else:
    paga += 1

if confianca_arvore >= confianca_minima:
  algoritmos += 1
  if resposta_arvore[0] == 1:
    nao_paga += 1
  else:
    paga += 1

if confianca_svm >= confianca_minima:
  algoritmos += 1
  if resposta_svm[0] == 1:
    nao_paga += 1
  else:
    paga += 1

if paga > nao_paga:
  print(f"Pagará o emprestimo, baseado em {algoritmos} algoritmos")
elif paga == nao_paga:
  print(f"Empate, baseado em {algoritmos} algoritmos")
else:
  print(f"Não paga o emprestimo, baseado em {algoritmos} algoritmos")

Pagará o emprestimo, baseado em 2 algoritimos
