In [10]:
import pickle

In [11]:
with open('credit.pkl', 'rb') as f:
  x_treinamento, y_treinamento, x_teste, y_teste = pickle.load(f)

In [12]:
import numpy as np

In [15]:
X_credit = np.concatenate((x_treinamento, x_teste), axis=0)
Y_credit = np.concatenate((y_treinamento, y_teste), axis=0)

# Carregando Modelos Salvos

In [7]:
!pip install skops
from skops.io import load

In [8]:
rede_neural = load('rede_neural_finalizada.skops', trusted=True)
arvore = load('arvore_finalizada.skops', trusted=True)
svm = load('svm_finalizada.skops', trusted=True)

In [16]:
novo_registro = X_credit[0]
novo_registro

array([-1.3754462 ,  0.50631087,  0.10980934])

In [17]:
novo_registro.shape

(3,)

In [18]:
novo_registro = novo_registro.reshape(1,-1)
novo_registro.shape

(1, 3)

In [19]:
rede_neural.predict(novo_registro)

array([0])

In [20]:
arvore.predict(novo_registro)

array([0])

In [21]:
svm.predict(novo_registro)

array([0])